### ISSUE TITLE
Change pin icon based on tree type.

### ISSUE THREAD

**Issue by tomcentrate** [cforlando/energy-saving-trees-ios#15]
@JWTechdev created some great pictures of trees, located in The #trees slackchat.
We used one of the trees to represent the icon.

We'll need to show different sets of trees with different icons.

Adding the trees to the /Assets folder.

**Comment by JWTechdev** [comment]
Hey @tomcentrate :) can you clarify I uploaded trees fro every type of tree to slack but request to push it the repo

**Comment by tomcentrate** [comment]
Hi @JWTechdev , thanks for the clarifications. I'll submit a PR to upload both icons and the Tree Images for the submission form.
