### ISSUE TITLE
[App] Confirmation Page

### ISSUE THREAD

**Issue by LondonAtlas** [cforlando/energy-saving-trees-ios#62]
Create a confirmation page that has three properties a tree object, an address object and a contact object.
Once the user taps "Send" convert the information from the passed objects into a Wufoo form found in the transport kit, and send the form back through a delegate(protocol)

Requirements:
View controller should have its own storyboard.
import StreetTreesTransportKit

![design-review](https://cloud.githubusercontent.com/assets/1647012/18809418/9bb074e6-8248-11e6-8b87-6fea15cf65b1.png)

**Comment by LondonAtlas** [comment]
For the purpose of building, create a test tree, location, and user object

**Comment by PedroTrujilloV** [comment]
Thanks.

**Comment by LondonAtlas** [comment]
Once the user presses send, segue to this view

![design-complete](https://cloud.githubusercontent.com/assets/1647012/19096363/ca80313e-8a69-11e6-81b3-ba4cd954b9a9.png)
