### ISSUE TITLE
[App] Swift 3.0

### ISSUE THREAD

**Issue by LondonAtlas** [cforlando/energy-saving-trees-ios#63]
Convert the application to Swift 3.0

**Comment by markfilter** [comment]
Pull request submitted for this issue.  As far as what I see in my build, the only two errors are the frame initializers for FBAnnotationClusterView.swift, which is locked.

**Comment by LondonAtlas** [comment]
A cocoa pods update is most likely required for to correct this.

**Comment by markfilter** [comment]
Unfortunately, the pod update did not fix the errors.

**Comment by LondonAtlas** [comment]
This sucked but it is done.
